### PR TITLE
Resolve hugo build issues

### LINKED ISSUE #5089: Bug: Hugo setup error on fresh install
**Describe the bug**
Website won't run locally on a fresh install.

**Steps to Reproduce**
1. Install node v14
2. Run `npm install`
3. Install Hugo via homebrew
4. `brew install hugo`
5. Run `npm start`
6. Confirm error

```bash
Error: add site dependencies: create deps: markup: Configured defaultMarkdownHandler "blackfriday" not found. Did you mean to use goldmark? Blackfriday was removed in Hugo v0.100.0.
```

**Screenshots**

image

### PR DESCRIPTION
**Pull request by mejiaj**
Closes #5089.  

This PR implements the following **changes:**

* Uses standard goldmark markdown handler [a9c72403577534f6b15acb30562b68b60ce24a7f]
* Allows markup rendering in markdown files  [a9c72403577534f6b15acb30562b68b60ce24a7f]
* Ignores vendor script `uswds-init` from jshint

⚠️ **Note** goldmark won't render markup in MD files without this flag:

```yml
markup:
  …
  goldmark:
    renderer:
      unsafe: true
```

**Without flag**

image

**With flag**

image

**URL / Link to page**

`2016/11/09/challenge-gov-launches-one-click-reporting-for-annual-prizes-data-call/`

### CODE REVIEW

File: config/gulp/scripts.js [hunk 1]
```diff
@@ -27,7 +27,9 @@ function compileCommon() {
 }
 
 function compile() {
-  return src([`${PROJECT_JS_SRC}/*.js`])
+  // TODO: Move USWDS init to a vendor directory.
+  // That way we can ignore vendor instead of individual files.
+  return src([`${PROJECT_JS_SRC}/*.js`, `!${PROJECT_JS_SRC}/uswds-init.min.js`])
```
Comment (mejiaj) [inline config/gulp/scripts.js:32]: `uswds-init.min.js` is a vendor file. Ignoring it in jshint because it shows 10 errors on `npm start` command.


**The errors**
```bash
10 errors
themes/digital.gov/src/js/uswds-init.min.js: line 1, col 195, Missing semicolon.
themes/digital.gov/src/js/uswds-init.min.js: line 1, col 195, Expected an identifier and instead saw '='.
themes/digital.gov/src/js/uswds-init.min.js: line 1, col 195, Expected an assignment or function call and instead saw an expression.
themes/digital.gov/src/js/uswds-init.min.js: line 1, col 196, Missing semicolon.
themes/digital.gov/src/js/uswds-init.min.js: line 1, col 215, Expected an assignment or function call and instead saw an expression.
themes/digital.gov/src/js/uswds-init.min.js: line 1, col 216, Missing semicolon.
themes/digital.gov/src/js/uswds-init.min.js: line 1, col 295, Missing semicolon.
themes/digital.gov/src/js/uswds-init.min.js: line 1, col 316, Expected an assignment or function call and instead saw an expression.
themes/digital.gov/src/js/uswds-init.min.js: line 1, col 317, Missing semicolon.
themes/digital.gov/src/js/uswds-init.min.js: line 1, col 217, 't' used out of scope.
themes/digital.gov/src/js/uswds-init.min.js: line 1, col 250, 't' used out of scope.
themes/digital.gov/src/js/uswds-init.min.js: line 1, col 297, 't' used out of scope.
themes/digital.gov/src/js/uswds-init.min.js: line 1, col 299, 't' used out of scope.
themes/digital.gov/src/js/uswds-init.min.js: line 1, col 337, Missing semicolon.
themes/digital.gov/src/js/uswds-init.min.js: line 1, col 419, Missing semicolon.
themes/digital.gov/src/js/uswds-init.min.js: line 1, col 565, Missing semicolon.
themes/digital.gov/src/js/uswds-init.min.js: line 1, col 800, Expected an assignment or function call and instead saw an expression.
themes/digital.gov/src/js/uswds-init.min.js: line 1, col 801, Missing semicolon.
themes/digital.gov/src/js/uswds-init.min.js: line 1, col 807, Missing semicolon.
themes/digital.gov/src/js/uswds-init.min.js: line 1, col 810, Expected an assignment or function call and instead saw an expression.
themes/digital.gov/src/js/uswds-init.min.js: line 1, col 811, Missing semicolon.
themes/digital.gov/src/js/uswds-init.min.js: line 1, col 824, Expected an assignment or function call and instead saw an expression.
```

File: content/news/2016/11/2016-11-09-challenge-gov-launches-one-click-reporting-for-annual-prizes-data-call.md [hunk 2]
```diff
@@ -2,7 +2,7 @@
 slug: challenge-gov-launches-one-click-reporting-for-annual-prizes-data-call
 date: 2016-11-09 5:43:18 -0400
 title: Challenge.gov Launches One-Click Reporting for Annual Prizes Data Call
-summary: 'This year, the deadline for agencies to submit their reporting of incentive prize competitions and challenges for FY16 comes earlier than most. Roughly two weeks from today, by Nov. 18, federal agencies are required to submit their accounts of every prize, competition, or challenge that launched, ran or completed in FY16 via email.  {{< legacy-img'
+summary: 'This year, the deadline for agencies to submit their reporting of incentive prize competitions and challenges for FY16 comes earlier than most. Roughly two weeks from today, by Nov. 18, federal agencies are required to submit their accounts of every prize, competition, or challenge that launched, ran or completed in FY16 via email.'
```
Comment (mejiaj) [inline content/news/2016/11/2016-11-09-challenge-gov-launches-one-click-reporting-for-annual-prizes-data-call.md:5]: The `{{< legacy-img'` was causing the build to fail locally.

Comment (nick-mon1) [reply content/news/2016/11/2016-11-09-challenge-gov-launches-one-click-reporting-for-annual-prizes-data-call.md:5]: Probably shouldn't be there anyways

**Review by nick-mon1 — COMMENTED** [review]
Looks good @mejiaj

**Review by nick-mon1 — APPROVED** [review]
